"""Adds email username to permissions

Revision ID: c6d50a04cf9d
Revises: 2523fa8f0b7b
Create Date: 2025-10-31 12:07:10.290670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d50a04cf9d'
down_revision: Union[str, Sequence[str], None] = '2523fa8f0b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('permissions', sa.Column('username', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_permissions_email'), 'permissions', ['email'], unique=True)
    op.create_index(op.f('ix_permissions_username'), 'permissions', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_username'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_email'), table_name='permissions')
    op.drop_column('permissions', 'username')
    op.drop_column('permissions', 'email')
    # ### end Alembic commands ###
