"""adds connection_id to uix_provider_connection_drive_item

Revision ID: e5ab1adc9113
Revises: a1b2c3d4e5f6
Create Date: 2025-11-19 15:49:57.399523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5ab1adc9113'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider_configs', 'provider',
               existing_type=sa.VARCHAR(length=50),
               comment="Provider type (e.g., 'sharepoint')",
               existing_nullable=False)
    op.alter_column('provider_configs', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Human-readable name',
               existing_nullable=False)
    op.alter_column('provider_configs', 'auth_url',
               existing_type=sa.VARCHAR(length=500),
               comment='OAuth authorization endpoint',
               existing_nullable=False)
    op.alter_column('provider_configs', 'token_url',
               existing_type=sa.VARCHAR(length=500),
               comment='OAuth token endpoint',
               existing_nullable=False)
    op.alter_column('provider_configs', 'graph_base_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Microsoft Graph API base URL',
               existing_nullable=False)
    op.alter_column('provider_configs', 'default_scopes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='Default OAuth scopes',
               existing_nullable=False)
    op.alter_column('provider_configs', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='DB-level kill switch',
               existing_nullable=False)
    op.drop_index(op.f('ix_provider_configs_provider'), table_name='provider_configs')
    op.create_unique_constraint(None, 'provider_configs', ['provider'])
    op.alter_column('provider_connections', 'tenant_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Microsoft 365 tenant ID',
               existing_nullable=False)
    op.alter_column('provider_connections', 'encrypted_tokens',
               existing_type=sa.TEXT(),
               comment='Fernet-encrypted token data',
               existing_nullable=False)
    op.alter_column('provider_item_refs', 'drive_id',
               existing_type=sa.VARCHAR(length=255),
               comment='SharePoint/OneDrive drive ID',
               existing_nullable=False)
    op.alter_column('provider_item_refs', 'item_id',
               existing_type=sa.VARCHAR(length=255),
               comment='SharePoint/OneDrive item ID',
               existing_nullable=False)
    op.alter_column('provider_item_refs', 'etag',
               existing_type=sa.VARCHAR(length=255),
               comment='Entity tag for change detection',
               existing_nullable=True)
    op.alter_column('provider_item_refs', 'content_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='QuickXorHash for content verification',
               existing_nullable=True)
    op.drop_index(op.f('uix_provider_drive_item'), table_name='provider_item_refs')
    op.create_index('uix_provider_connection_drive_item', 'provider_item_refs', ['provider', 'connection_id', 'drive_id', 'item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_provider_connection_drive_item', table_name='provider_item_refs')
    op.create_index(op.f('uix_provider_drive_item'), 'provider_item_refs', ['provider', 'drive_id', 'item_id'], unique=True)
    op.alter_column('provider_item_refs', 'content_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='QuickXorHash for content verification',
               existing_nullable=True)
    op.alter_column('provider_item_refs', 'etag',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Entity tag for change detection',
               existing_nullable=True)
    op.alter_column('provider_item_refs', 'item_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='SharePoint/OneDrive item ID',
               existing_nullable=False)
    op.alter_column('provider_item_refs', 'drive_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='SharePoint/OneDrive drive ID',
               existing_nullable=False)
    op.alter_column('provider_connections', 'encrypted_tokens',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Fernet-encrypted token data',
               existing_nullable=False)
    op.alter_column('provider_connections', 'tenant_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Microsoft 365 tenant ID',
               existing_nullable=False)
    op.drop_constraint(None, 'provider_configs', type_='unique')
    op.create_index(op.f('ix_provider_configs_provider'), 'provider_configs', ['provider'], unique=True)
    op.alter_column('provider_configs', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='DB-level kill switch',
               existing_nullable=False)
    op.alter_column('provider_configs', 'default_scopes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='Default OAuth scopes',
               existing_nullable=False)
    op.alter_column('provider_configs', 'graph_base_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Microsoft Graph API base URL',
               existing_nullable=False)
    op.alter_column('provider_configs', 'token_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='OAuth token endpoint',
               existing_nullable=False)
    op.alter_column('provider_configs', 'auth_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='OAuth authorization endpoint',
               existing_nullable=False)
    op.alter_column('provider_configs', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Human-readable name',
               existing_nullable=False)
    op.alter_column('provider_configs', 'provider',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Provider type (e.g., 'sharepoint')",
               existing_nullable=False)
    # ### end Alembic commands ###
