name: Health Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  health-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg15
        env:
          POSTGRES_DB: ragdb
          POSTGRES_USER: raguser
          POSTGRES_PASSWORD: changeme
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      minio:
        image: minio/minio
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1"
          --health-interval 30s
          --health-timeout 20s
          --health-retries 3

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install redis-cli for connectivity check
      run: |
        sudo apt-get update
        sudo apt-get install -y redis-tools postgresql-client

    - name: Check service connectivity
      run: |
        # Check PostgreSQL
        pg_isready -h localhost -p 5432 -U raguser

        # Check Redis
        redis-cli -h localhost -p 6379 ping

        # Check MinIO
        curl -f http://localhost:9000/minio/health/live

    - name: Create MinIO bucket
      run: |
        # Install MinIO client
        wget -q https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        ./mc alias set local http://localhost:9000 minioadmin minioadmin
        ./mc mb local/documents --ignore-existing || true

    - name: Initialize database
      working-directory: ./server
      run: |
        PGPASSWORD=changeme psql -h localhost -U raguser -d ragdb -f init.sql
      env:
        DATABASE_URL: postgresql+psycopg://raguser:changeme@localhost:5432/ragdb

    - name: Start FastAPI server and test health endpoint
      working-directory: ./server
      run: |
        python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        SERVER_PID=$!

        # Wait for server to start
        sleep 10

        # Test health endpoint
        curl -f http://localhost:8000/health

        # Test API documentation endpoint
        curl -f http://localhost:8000/docs

        # Stop server
        kill $SERVER_PID
      env:
        DATABASE_URL: postgresql+psycopg://raguser:changeme@localhost:5432/ragdb
        REDIS_URL: redis://localhost:6379/0
        MINIO_ENDPOINT: localhost:9000
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        MINIO_BUCKET: documents
        JWT_SECRET_KEY: test-secret-key-for-health-check
        JWT_ALGORITHM: HS256
        JWT_EXPIRATION_MINUTES: 30
        OPENAI_API_KEY: test-openai-key
        APP_NAME: RAG RBAC Health Check
        DEBUG: true
