name: UI Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ui-lint-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: |
          client/node_modules
          client/.next/cache
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('client/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        cd client
        npm ci

    - name: Run ESLint
      run: |
        cd client
        npm run lint
      continue-on-error: false

    - name: Build Next.js application
      run: |
        cd client
        npm run build
      env:
        # Minimal environment variables for build
        NEXT_PUBLIC_API_URL: http://localhost:8000
        NEXT_PUBLIC_APP_NAME: RADEX
        NEXT_PUBLIC_MAX_FILE_SIZE: 10485760
        NEXT_PUBLIC_ENABLE_MICROSOFT_LOGIN: false
        NEXT_PUBLIC_ENABLE_OKTA_LOGIN: false
        NEXT_PUBLIC_FIREBASE_API_KEY: test-api-key
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: test.firebaseapp.com
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: test-project
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: test.appspot.com
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 123456789
        NEXT_PUBLIC_FIREBASE_APP_ID: 1:123456789:web:test
        NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: G-TEST123

    - name: Check build output
      run: |
        cd client
        if [ -d ".next" ]; then
          echo "✅ Build successful - .next directory created"
          ls -la .next
        else
          echo "❌ Build failed - .next directory not found"
          exit 1
        fi

    - name: Validation Summary
      if: always()
      run: |
        echo "## UI Validation Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Node.js version:** ${{ matrix.node-version }}" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ All checks passed!" >> $GITHUB_STEP_SUMMARY
          echo "- ESLint validation passed" >> $GITHUB_STEP_SUMMARY
          echo "- Next.js build completed successfully" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Validation failed" >> $GITHUB_STEP_SUMMARY
          echo "Please check the logs above for details" >> $GITHUB_STEP_SUMMARY
        fi
